// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ6RvTUYm7wwq-JNYV_x32aNK_ZPOQW88',
    appId: '1:964509505090:android:3e9b1afe23ef8ee087bfdb',
    messagingSenderId: '964509505090',
    projectId: 'tamago-ta',
    databaseURL: 'https://tamago-ta-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tamago-ta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD12wGgymLqPh_pKlfirVaWbXE9GPU1wfE',
    appId: '1:964509505090:ios:46a961383c51d9ad87bfdb',
    messagingSenderId: '964509505090',
    projectId: 'tamago-ta',
    databaseURL: 'https://tamago-ta-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tamago-ta.appspot.com',
    iosBundleId: 'com.example.tamagofishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD12wGgymLqPh_pKlfirVaWbXE9GPU1wfE',
    appId: '1:964509505090:ios:d8b06848070eea2087bfdb',
    messagingSenderId: '964509505090',
    projectId: 'tamago-ta',
    databaseURL: 'https://tamago-ta-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tamago-ta.appspot.com',
    iosBundleId: 'com.example.tamagofishApp.RunnerTests',
  );
}
